sonar.projectKey=demo-app
sonar.projectName=demo-app

sonar.sources=demo-app/src/main/java
sonar.tests=demo-app/src/test/java

sonar.java.binaries=demo-app/target/classes
sonar.java.test.binaries=demo-app/target/test-classes
